{{- if .Values.manifests.daemonset_webui }}
{{- $_ := set .Values "images" .Values.global.images }}
{{- $context := . }}
{{- $dependencies := .Values.dependencies.webui }}

{{- $serviceAccountName := "webui" }}
{{ tuple $context $dependencies $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}
{{ tuple $context $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_csr_role" }}
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: tf-webui
spec:
{{ tuple $context "webui" | include "helm-toolkit.snippets.kubernetes_upgrades_daemonset" | indent 2 }}
  template:
    metadata:
      labels:
{{ tuple $context "tungstenfabric" "tf-webui" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
        configmap-hash: {{ tuple "configmap-env.yaml" $context | include "helm-toolkit.utils.hash" }}
    spec:
      serviceAccountName: {{ $serviceAccountName }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.labels.webui.node_selector_key }}
                operator: In
                values:
                - {{ .Values.labels.webui.node_selector_value }}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
        - name: tf-controller-docker-secret
      initContainers:
{{ tuple $context $dependencies nil | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
        - name: tf-node-init
          image: {{ .Values.global.images.tags.node_init | quote }}
          imagePullPolicy: {{ default "" .Values.global.images.imagePullPolicy | quote }}
          securityContext:
            privileged: true
          env:
          - name: CONTRAIL_STATUS_IMAGE
            value: {{ .Values.global.images.tags.tf_status | quote }}
          envFrom:
          - configMapRef:
              name: tf-controller-env
          volumeMounts:
          - mountPath: /host/usr/bin
            name: host-usr-bin
          - mountPath: /etc/contrail/ssl
            name: ssl-dir
          - mountPath: /etc/sysctl.conf
            name: host-sysctl-conf
      containers:
      - name: tf-webui-middleware
        image: {{ .Values.global.images.tags.webui_middleware | quote }}
        imagePullPolicy: {{ default "" .Values.global.images.imagePullPolicy | quote }}
        ports:
        - name: http-port
          containerPort: {{ .Values.global.tf_env.WEBUI_HTTP_LISTEN_PORT | default 8080 }}
        - name: https-port
          containerPort: {{ .Values.global.tf_env.WEBUI_HTTPS_LISTEN_PORT | default 8143 }}
        envFrom:
        - configMapRef:
            name: tf-controller-env
        - configMapRef:
            name: tf-controller-keystone
        env:
        - name: KEYSTONE_AUTH_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.keystone.admin }}
              key: KEYSTONE_AUTH_ADMIN_PASSWORD
        volumeMounts:
        - mountPath: /var/log/contrail/
          name: tf-log
        - mountPath: /var/crashes
          name: var-crashes-webui
        - mountPath: /etc/contrail/ssl
          name: ssl-dir
        {{- if and (.Values.global.tf_env.WEBUI_SSL_CERT_FILE) (.Values.global.tf_env.WEBUI_SSL_KEY_FILE) }}
        - mountPath: {{ .Values.global.tf_env.WEBUI_SSL_CERT_DIR | quote }}
          name: webui-certificate
          readOnly: true
        {{- end }}
      - name: tf-webui
        image: {{ .Values.global.images.tags.webui | quote }}
        imagePullPolicy: {{ default "" .Values.global.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: tf-controller-env
        - configMapRef:
            name: tf-controller-keystone
        env:
        - name: KEYSTONE_AUTH_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.keystone.admin }}
              key: KEYSTONE_AUTH_ADMIN_PASSWORD
        volumeMounts:
        - mountPath: /var/log/contrail/
          name: tf-log
        - mountPath: /var/crashes
          name: var-crashes-webui
        - mountPath: /etc/contrail/ssl
          name: ssl-dir
        {{- if and (.Values.global.tf_env.WEBUI_SSL_CERT_FILE) (.Values.global.tf_env.WEBUI_SSL_KEY_FILE) }}
        - mountPath: {{ .Values.global.tf_env.WEBUI_SSL_CERT_DIR | quote }}
          name: webui-certificate
          readOnly: true
        {{- end }}
      volumes:
      - name: tf-log
        hostPath:
          path: /var/log/contrail
      - name: var-crashes-webui
        hostPath:
          path: /var/crashes/contrail/webui
      - name: host-usr-bin
        hostPath:
          path: {{ .Values.volumeMounts.host_usr_bin.hostPath }}
      - name: ssl-dir
        hostPath:
          path: /etc/contrail/ssl
      - name: host-sysctl-conf
        hostPath:
          path: /etc/sysctl.conf
      {{- if and (.Values.global.tf_env.WEBUI_SSL_CERT_FILE) (.Values.global.tf_env.WEBUI_SSL_KEY_FILE) }}
      - name: webui-certificate
        hostPath:
          path: {{ .Values.global.tf_env.WEBUI_SSL_CERT_DIR | quote }}
      {{- end }}
{{- end }}
